version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    branches:
        only:
          - dev

    working_directory: /go/src/github.com/wasuken/slack-memo-bot
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      # push master
      - run: git config user.email "wevorence@gmail.com"
      - run: git config user.name "circleci"
      - run: git checkout -b origin/master
      - run: git merge dev
      - run: git push origin master
